=== rhobert/MolSim/src/input/InputParameters.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www5.in.tum.de/wiki/index.php/PSE_Molekulardynamik_WS12"
xmlns="http://www5.in.tum.de/wiki/index.php/PSE_Molekulardynamik_WS12"
elementFormDefault="qualified">

	<xs:simpleType name="nonEmptyString_t">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="positiveDecimal_t">
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="inputType_t">
		<xs:restriction base="xs:string">
			<xs:enumeration value="list" />
			<xs:enumeration value="cuboid" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="inputFile_t">
		<xs:simpleContent>
			<xs:extension base="nonEmptyString_t">
				<xs:attribute name="type" type="inputType_t" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="inputFiles_t">
		<xs:sequence>
			<xs:element name="inputFile" type="inputFile_t" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="potential_t">
		<xs:restriction base="xs:string">
			<xs:enumeration value="gravitational" />
			<xs:enumeration value="lenard jones" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="simulation_t">
		<xs:all>
			<xs:element name="outputFile" type="nonEmptyString_t" />
			<xs:element name="inputFiles" type="inputFiles_t" />
			<xs:element name="writeFrequency" type="xs:positiveInteger" />
			<xs:element name="t_end" type="positiveDecimal_t" />
			<xs:element name="delta_t" type="positiveDecimal_t" />
			<xs:element name="potential" type="potential_t" />
		</xs:all>	
	</xs:complexType>
	
	<xs:element name="simulation" type="simulation_t" />

</xs:schema>

=== rhobert/MolSim/input.xml
<?xml version="1.0"?>

<simulation xmlns="http://www5.in.tum.de/wiki/index.php/PSE_Molekulardynamik_WS12"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www5.in.tum.de/wiki/index.php/PSE_Molekulardynamik_WS12 src/input/InputParameters.xsd">
	<outputFile>MD</outputFile>
	<inputFiles>
		<inputFile type="cuboid">eingabe-molekuel.txt</inputFile>
	</inputFiles>
	<writeFrequency>10</writeFrequency>
	<t_end>3.0</t_end>
	<delta_t>0.0003</delta_t>
	<potential>lenard jones</potential>
</simulation>
